// <auto-generated />
using System;
using Final_Test_Hybrid.Services.Database.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Final_Test_Hybrid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251230161806_AddBoilerAndOperation")]
    partial class AddBoilerAndOperation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Boiler", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BoilerTypeCycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_TYPE_CYCLE_ID");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE_CREATE");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE_UPDATE");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("OPERATOR");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SERIAL_NUMBER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("BoilerTypeCycleId")
                        .HasDatabaseName("IDX_TB_BOILER_BOILER_TYPE_CYCLE");

                    b.HasIndex("DateCreate")
                        .HasDatabaseName("IDX_TB_BOILER_DATE_CREATE");

                    b.HasIndex("DateUpdate")
                        .HasDatabaseName("IDX_TB_BOILER_DATE_UPDATE");

                    b.HasIndex("Operator")
                        .HasDatabaseName("IDX_TB_BOILER_OPERATOR");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_BOILER_UNQ_SERIAL_NUMBER");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_TB_BOILER_STATUS");

                    b.ToTable("TB_BOILER", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.BoilerType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ARTICLE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("Article")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_BOILER_TYPE_UNQ_ARTICLE");

                    b.ToTable("TB_BOILER_TYPE", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.BoilerTypeCycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ARTICLE");

                    b.Property<long>("BoilerTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_TYPE_ID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_BOILER_TYPE_CYCLE_UNQ_ACTIVE")
                        .HasFilter("\"IS_ACTIVE\" = true");

                    b.ToTable("TB_BOILER_TYPE_CYCLE", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.ErrorSettingsHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressError")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ADDRESS_ERROR");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long?>("ErrorSettingsTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ERROR_SETTINGS_TEMPLATE_ID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<long?>("StepHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("STEP_HISTORY_ID");

                    b.HasKey("Id");

                    b.HasIndex("AddressError")
                        .HasDatabaseName("IDX_TB_ERROR_SETTINGS_HISTORY_ADDRESS_ERROR");

                    b.HasIndex("ErrorSettingsTemplateId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_ERROR_SETTINGS_HISTORY_UNQ_ACTIVE")
                        .HasFilter("\"IS_ACTIVE\" = true");

                    b.HasIndex("StepHistoryId")
                        .HasDatabaseName("IDX_TB_ERROR_SETTINGS_HISTORY_STEP_HISTORY");

                    b.ToTable("TB_ERROR_SETTINGS_HISTORY", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.ErrorSettingsTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressError")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ADDRESS_ERROR");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long?>("StepId")
                        .HasColumnType("bigint")
                        .HasColumnName("STEP_ID");

                    b.HasKey("Id");

                    b.HasIndex("AddressError")
                        .HasDatabaseName("IDX_TB_ERROR_SETTINGS_TEMPLATE_ADDRESS_ERROR");

                    b.HasIndex("StepId")
                        .HasDatabaseName("IDX_TB_ERROR_SETTINGS_TEMPLATE_STEP");

                    b.HasIndex("AddressError", "StepId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_ERROR_SETTINGS_TEMPLATE_UNQ_ADDRESS_ERROR_STEP");

                    b.ToTable("TB_ERROR_SETTINGS_TEMPLATE", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Operation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BoilerId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_ID");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("COMMENT_");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE_END");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATE_START");

                    b.Property<int>("NumberShift")
                        .HasColumnType("integer")
                        .HasColumnName("NUMBER_SHIFT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("OPERATOR");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("STATUS");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("BoilerId")
                        .HasDatabaseName("IDX_TB_OPERATION_BOILER");

                    b.HasIndex("DateEnd")
                        .HasDatabaseName("IDX_TB_OPERATION_DATE_END");

                    b.HasIndex("DateStart")
                        .HasDatabaseName("IDX_TB_OPERATION_DATE_START");

                    b.HasIndex("Operator")
                        .HasDatabaseName("IDX_TB_OPERATION_OPERATOR");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_TB_OPERATION_STATUS");

                    b.HasIndex("BoilerId", "DateStart")
                        .HasDatabaseName("IDX_TB_OPERATION_BOILER_DATE_START");

                    b.ToTable("TB_OPERATION", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS");

                    b.Property<long>("BoilerTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_TYPE_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsPlc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PLC");

                    b.Property<string>("PlcType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PLC_TYPE");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TAG_NAME");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UNIT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("BoilerTypeId")
                        .HasDatabaseName("IDX_TB_RECIPE_BOILER_TYPE");

                    b.HasIndex("Address", "BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_RECIPE_UNQ_ADDRESS_BOILER_TYPE");

                    b.HasIndex("TagName", "BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_RECIPE_UNQ_TAG_NAME_BOILER_TYPE");

                    b.ToTable("TB_RECIPE", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.ResultSettingHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressMax")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_MAX");

                    b.Property<string>("AddressMin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_MIN");

                    b.Property<string>("AddressStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_STATUS");

                    b.Property<string>("AddressValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_VALUE");

                    b.Property<string>("AuditType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("AUDIT_TYPE");

                    b.Property<long>("BoilerTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_TYPE_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Nominal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("NOMINAL");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PARAMETER_NAME");

                    b.Property<string>("PlcType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PLC_TYPE");

                    b.Property<long>("ResultsSettingsId")
                        .HasColumnType("bigint")
                        .HasColumnName("RESULTS_SETTINGS_ID");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UNIT");

                    b.HasKey("Id");

                    b.HasIndex("BoilerTypeId")
                        .HasDatabaseName("IDX_TB_RESULT_SETTING_HISTORY_BOILER_TYPE");

                    b.HasIndex("ResultsSettingsId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_RESULT_SETTING_HISTORY_UNQ_ACTIVE")
                        .HasFilter("\"IS_ACTIVE\" = true");

                    b.ToTable("TB_RESULT_SETTING_HISTORY", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.ResultSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressMax")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_MAX");

                    b.Property<string>("AddressMin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_MIN");

                    b.Property<string>("AddressStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_STATUS");

                    b.Property<string>("AddressValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS_VALUE");

                    b.Property<string>("AuditType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("AUDIT_TYPE");

                    b.Property<long>("BoilerTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_TYPE_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Nominal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("NOMINAL");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PARAMETER_NAME");

                    b.Property<string>("PlcType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PLC_TYPE");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UNIT");

                    b.HasKey("Id");

                    b.HasIndex("AddressMin")
                        .HasDatabaseName("IDX_TB_RESULT_SETTINGS_ADDRESS_MIN");

                    b.HasIndex("BoilerTypeId")
                        .HasDatabaseName("IDX_TB_RESULT_SETTINGS_BOILER_TYPE");

                    b.HasIndex("AddressValue", "BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_RESULT_SETTINGS_UNQ_ADDRESS_VALUE_BOILER_TYPE");

                    b.HasIndex("ParameterName", "BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_RESULT_SETTINGS_UNQ_PARAMETER_NAME_BOILER_TYPE");

                    b.ToTable("TB_RESULT_SETTINGS", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.StepFinalTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_STEP_FINAL_TEST_UNQ_NAME");

                    b.ToTable("TB_STEP_FINAL_TEST", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.StepFinalTestHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("NAME");

                    b.Property<long>("StepFinalTestId")
                        .HasColumnType("bigint")
                        .HasColumnName("STEP_FINAL_TEST_ID");

                    b.HasKey("Id");

                    b.HasIndex("StepFinalTestId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_STEP_FINAL_TEST_HISTORY_UNQ_ACTIVE")
                        .HasFilter("\"IS_ACTIVE\" = true");

                    b.ToTable("TB_STEP_FINAL_TEST_HISTORY", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Boiler", b =>
                {
                    b.HasOne("Final_Test_Hybrid.Models.Database.BoilerTypeCycle", "BoilerTypeCycle")
                        .WithMany()
                        .HasForeignKey("BoilerTypeCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoilerTypeCycle");
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.ErrorSettingsHistory", b =>
                {
                    b.HasOne("Final_Test_Hybrid.Models.Database.StepFinalTestHistory", "StepHistory")
                        .WithMany()
                        .HasForeignKey("StepHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StepHistory");
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.ErrorSettingsTemplate", b =>
                {
                    b.HasOne("Final_Test_Hybrid.Models.Database.StepFinalTest", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Operation", b =>
                {
                    b.HasOne("Final_Test_Hybrid.Models.Database.Boiler", "Boiler")
                        .WithMany()
                        .HasForeignKey("BoilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boiler");
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Recipe", b =>
                {
                    b.HasOne("Final_Test_Hybrid.Models.Database.BoilerType", "BoilerType")
                        .WithMany()
                        .HasForeignKey("BoilerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoilerType");
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.ResultSettings", b =>
                {
                    b.HasOne("Final_Test_Hybrid.Models.Database.BoilerType", "BoilerType")
                        .WithMany()
                        .HasForeignKey("BoilerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoilerType");
                });
#pragma warning restore 612, 618
        }
    }
}
