// <auto-generated />
using Final_Test_Hybrid.Services.Database.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Final_Test_Hybrid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.BoilerType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ARTICLE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TYPE");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("Article")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_BOILER_TYPE_UNQ_ARTICLE");

                    b.ToTable("TB_BOILER_TYPE", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.BoilerTypeCycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ARTICLE");

                    b.Property<long>("BoilerTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_TYPE_ID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TYPE");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_BOILER_TYPE_CYCLE_UNQ_ACTIVE")
                        .HasFilter("\"IS_ACTIVE\" = true");

                    b.ToTable("TB_BOILER_TYPE_CYCLE", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ADDRESS");

                    b.Property<long>("BoilerTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("BOILER_TYPE_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsPlc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PLC");

                    b.Property<string>("PlcType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PLC_TYPE");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TAG_NAME");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UNIT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("VALUE");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("BoilerTypeId")
                        .HasDatabaseName("IDX_TB_RECIPE_BOILER_TYPE");

                    b.HasIndex("Address", "BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_RECIPE_UNQ_ADDRESS_BOILER_TYPE");

                    b.HasIndex("TagName", "BoilerTypeId")
                        .IsUnique()
                        .HasDatabaseName("IDX_TB_RECIPE_UNQ_TAG_NAME_BOILER_TYPE");

                    b.ToTable("TB_RECIPE", (string)null);
                });

            modelBuilder.Entity("Final_Test_Hybrid.Models.Database.Recipe", b =>
                {
                    b.HasOne("Final_Test_Hybrid.Models.Database.BoilerType", "BoilerType")
                        .WithMany()
                        .HasForeignKey("BoilerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoilerType");
                });
#pragma warning restore 612, 618
        }
    }
}
